name: UcmaPluginTurkish
main: MuthisO\MuthisO
api: 3.8.1
version: 0.1
author: Müthiş Oyuncu
commands:
  uc:
    description: Uçma Eklentisi/Fly plugin (Müthiş Oyuncu)
permissions:
  ucac.kmt:
    default: op
  uckapa.kmt:
    default: op